### PR TITLE
Splash, SignIn, Signup , Forgot Password(Ui only)

### PR DESCRIPTION
**Pull request by sabdar18**
Added Network permission to Android manifest file

### CODE REVIEW

**Comment by sabdar18** [comment]
Added Network connection , whether connected to wifi or mobile 
and whether connected to network connection

**Comment by sabdar18** [comment]
Added Colour Scheme as mentioned 

Added Splash Screen as per the proto type reference 

https://pr.to/7T5LBD/?ap=1

**Comment by sabdar18** [comment]
Added SignIn Activity User Interface 

sign_in

**Comment by sabdar18** [comment]
signup activity user interface completed 
signup

**Comment by sabdar18** [comment]
Forgot Password Activity User Interface  Completed 
but the logo not followed in the proto (placed same logo like signin, signup ui)
forgot_pass

**Comment by OjasviBhargava** [comment]
Thanks for contributing @sabdar18! We will surely review the code

**Comment by piedcipher** [comment]
Great Job! @sabdar18 :+1: :heart: Thank you for contributing.

**Comment by sabdar18** [comment]
login and sign up actvities logic added to login and create account with firebase ( also updating name to fireabase profile after account created)

**Comment by sabdar18** [comment]
Added Forgot password login to sent a reset email

**Comment by piedcipher** [comment]
Thank you for contributing @sabdar18 :+1: :smiley: 
Merged #32

**Pull request merged**
