### PR TITLE
Added onBoarding

### PR DESCRIPTION
**Pull request by lifeLessCoder**
Slackid : **@livelyCoder**

Added onBoarding following the prototype. 

1. No use of external libraries.

2. Handled showing up of the onboarding only the first time the user launches the app. 

3. Handled the correct order of launching activities. When the app is opened for the first time, first the splash screen is launched, then the onboarding and then sign-in and home screen.  The next time user launches the app, the same order is followed without the onboarding and sign in.

onboarding_women_safety 1

### CODE REVIEW

**Comment by vaishnavi-janardhan** [comment]
Thank you for your contribution @lifeLessCoder.
We have now provided links to the XML files and PNG images for the OnBoarding activity. You can use them in your submission and open a PR again.

**Comment by piedcipher** [comment]
I agree with @vaishnavi-janardhan. Also no need to create a new PR, you can push new commits to fork and new changes will get added to this PR. Thank you for contributing @lifeLessCoder :+1:

**Comment by lifeLessCoder** [comment]
@vaishnavi-janardhan , @piedcipher I have pushed new commits to my fork by adding high density drawables. Welcome :)

**Comment by piedcipher** [comment]
Great work @lifeLessCoder! :star2: :heart: Thank you for contributing :+1: 
Merged #66

**Pull request merged**
