### PR TITLE
Shivudevbranch

### PR DESCRIPTION
**Pull request by shiv-u**
I have made changes in splash_activity.xml,gradle files,strings.xml.But i can't find any conflicting issues in homeactivity.java or splashactivity.java.

### CODE REVIEW

**Comment by shiv-u** [comment]
I am not able to find issues in any of my above files , if found please help me in resolving it.

**Comment by piedcipher** [comment]
@shiv-u Please resolve merge conflicts.

**Comment by shiv-u** [comment]
@piedcipher  I am not able to find the conflicts , it would be great if you help in finding them.

**Comment by piedcipher** [comment]
It seems you've created branch **shivudevbranch** from **master** branch, that's why there are merge conflicts.

**Comment by shiv-u** [comment]
So what to do now.

**Comment by piedcipher** [comment]
Push everything to development branch of your fork and send a new PR. I'm closing this one.
Closed #52.

**Pull request closed without merging**
