### PR TITLE
Navigation Drawer, Bottom Navigation Drawer With All Blank Fragments

### PR DESCRIPTION
**Pull request by sabdar18**
Navigation Drawer added 
Bottom Navigation Bar Added
All Blank Fragments Also Added
navigatrion_drawer
home page
track_me

### CODE REVIEW

**Comment by piedcipher** [comment]
Great work @sabdar18! :star2: Thank you for contributing :+1:

**Comment by sabdar18** [comment]
I think there is need of home in the navigation drawer 
Modified Layout to new Requirements and design
Added glide to show images 
Added navigation drawer with profileimage, profile name, profile email
if profile image not present then it will show default logo  (for users login with email and password , and those users with no profile image on google)
navigatrion_drawer

**Comment by OjasviBhargava** [comment]
Thanks @sabdar18 for your contribution

**Comment by OjasviBhargava** [comment]
Closed #59

**Pull request closed without merging**
