### PR TITLE
Development

### PR DESCRIPTION
**Pull request by njha6185**
Added splash screen and change splash activity to appear first in manifest file.
@Nitish

screenshot_20180423-005625

### CODE REVIEW

**Comment by kkdroidgit** [comment]
@njha6185 Thanks for contributing. Though since it's a Splash Activity, try to make the style of Activity `NoActionBar`.

**Comment by njha6185** [comment]
Added NoActionBar theme in splash screen and LightActionBar in mainactivity.
@Nitish


screenshot_20180423-121923

**Comment by piedcipher** [comment]
@njha6185 Please resolve the merge conflicts.

**Comment by piedcipher** [comment]
Thank you for contributing :+1:
Closed #14.

**Pull request closed without merging**
