### PR TITLE
Update Splash Activity 

### PR DESCRIPTION
**Pull request by sabdar18**
Removed the handler with delay
Removed the activity_splash.xml
added the splash_background.xml to show the splash screen
added Style `SplashTheme` in Styles.xml, and applied to SplashActivity in AndroidManifest.xml

@SABDAR SHAIK

### CODE REVIEW

**Comment by piedcipher** [comment]
Hello @sabdar18, Thank you for contributing. App is crashing on my device.

**Comment by kartikohri1712** [comment]
@sabdar18 There is a resource not found error in splash_background.xml . Copy the ic_launcher.png to drawable folder and assign it as src attribute and You will be good to go.

**Comment by sabdar18** [comment]
#4  @piedcipher @kartikohri1712  
Updated spalsh_background.xml with new image and image added in drawable folder

**Comment by piedcipher** [comment]
Thank you for contributing :+1:
Closed #4.

**Pull request closed without merging**
