### PR TITLE
Design The Navigation Drawer using the constraint Layout

### PR DESCRIPTION
**Pull request by modfa**
Slack ID- MODF
- Design the navigation drawer and header with the constraint layout.
- added circular and navigation arc dependencies
screenshot_20180505-135826

### CODE REVIEW

**Comment by modfa** [comment]
Slack Handle- MODF
- Designed and added codes for the Navigation Drawer and used Constraint Layout, also added vector assets for menu items.
- Designed the BNV using the constraint layout and added the vector asset for menu item too.
- Designed the SOS image.
screenshot_20180506-164530
screenshot_20180506-164541

**Comment by piedcipher** [comment]
Great work @modfa :star2: Thank you for contributing :+1:

**Comment by OjasviBhargava** [comment]
Thanks @modfa for your contribution.

**Comment by OjasviBhargava** [comment]
Closed #61

**Pull request closed without merging**
